import os


# IMAGE CONSTANTS
DEFAULT_MAX_HEIGHT = 4000.0
DEFAULT_MAX_WIDTH = 4000.0
COPYRIGHT_MAX_HEIGHT = 560.0
COPYRIGHT_MAX_WIDTH = 843.0
PYTIF_TILE_WIDTH = 512
PYTIF_TILE_HEIGHT = 512
# pixels per millimeter; equiv. 300 DPI
DPI_VALUE = 11.812
COMPRESSION_TYPE = 'deflate'

# BUCKET SETTINGS
# Image sources and destination buckets
RBSC_BUCKET = os.environ['RBSC_BUCKET']
IMAGE_BUCKET = os.environ['IMAGE_BUCKET']
PROCESS_BUCKET = os.environ['PROCESS_BUCKET']
